replicaCount: 3
ingress:
  env: production
  hosts:
  - host: api.production.onloyalty.co.nz
    paths: # TODO update API_PATH
    - path: /1/<API_PATH>*
  - host: api.onloyaltynz.com
    paths: # TODO update API_PATH
    - path: /1/<API_PATH>*
